import { Stock } from "../types/stock";

//existing hardcoded stock details
export const localStocks: Stock[] = [
  {
    symbol: "HDFCBANK.NS",
    name: "HDFC Bank",
    sector: "Financial",
    exchange: "NSE",
    purchasePrice: 1500,
    quantity: 10,
    cmp: 0,
    peRatio: 0,
    earnings: "",
  },
  {
    symbol: "ICICIBANK.NS",
    name: "ICICI Bank",
    sector: "Financial",
    exchange: "NSE",
    purchasePrice: 900,
    quantity: 12,
    cmp: 0,
    peRatio: 0,
    earnings: "",
  },
  {
    symbol: "KOTAKBANK.NS",
    name: "Kotak Mahindra Bank",
    sector: "Financial",
    exchange: "NSE",
    purchasePrice: 1800,
    quantity: 6,
    cmp: 0,
    peRatio: 0,
    earnings: "",
  },
  {
    symbol: "RELIANCE.NS",
    name: "Reliance Industries",
    sector: "Energy",
    exchange: "NSE",
    purchasePrice: 2400,
    quantity: 5,
    cmp: 0,
    peRatio: 0,
    earnings: "",
  },
  {
    symbol: "ONGC.NS",
    name: "ONGC",
    sector: "Energy",
    exchange: "NSE",
    purchasePrice: 180,
    quantity: 40,
    cmp: 0,
    peRatio: 0,
    earnings: "",
  },
  {
    symbol: "TCS.NS",
    name: "TCS",
    sector: "Tech",
    exchange: "NSE",
    purchasePrice: 3200,
    quantity: 4,
    cmp: 0,
    peRatio: 0,
    earnings: "",
  },
  {
    symbol: "INFY.NS",
    name: "Infosys",
    sector: "Tech",
    exchange: "NSE",
    purchasePrice: 1400,
    quantity: 7,
    cmp: 0,
    peRatio: 0,
    earnings: "",
  },
  {
    symbol: "WIPRO.NS",
    name: "Wipro",
    sector: "Tech",
    exchange: "NSE",
    purchasePrice: 400,
    quantity: 20,
    cmp: 0,
    peRatio: 0,
    earnings: "",
  },
  {
    symbol: "SUNPHARMA.NS",
    name: "Sun Pharma",
    sector: "Healthcare",
    exchange: "NSE",
    purchasePrice: 1100,
    quantity: 8,
    cmp: 0,
    peRatio: 0,
    earnings: "",
  },
  {
    symbol: "DRREDDY.NS",
    name: "Dr Reddy’s Labs",
    sector: "Healthcare",
    exchange: "NSE",
    purchasePrice: 5200,
    quantity: 2,
    cmp: 0,
    peRatio: 0,
    earnings: "",
  },
  {
    symbol: "HINDUNILVR.NS",
    name: "Hindustan Unilever",
    sector: "FMCG",
    exchange: "NSE",
    purchasePrice: 2600,
    quantity: 4,
    cmp: 0,
    peRatio: 0,
    earnings: "",
  },
  {
    symbol: "ITC.NS",
    name: "ITC",
    sector: "FMCG",
    exchange: "NSE",
    purchasePrice: 420,
    quantity: 25,
    cmp: 0,
    peRatio: 0,
    earnings: "",
  },

  {
    symbol: "MARUTI.NS",
    name: "Maruti Suzuki",
    sector: "Auto",
    exchange: "NSE",
    purchasePrice: 10500,
    quantity: 1,
    cmp: 0,
    peRatio: 0,
    earnings: "",
  },
  {
    symbol: "BHARTIARTL.NS",
    name: "Bharti Airtel",
    sector: "Telecom",
    exchange: "NSE",
    purchasePrice: 950,
    quantity: 10,
    cmp: 0,
    peRatio: 0,
    earnings: "",
  },
  {
    symbol: "LT.NS",
    name: "Larsen & Toubro",
    sector: "Infra",
    exchange: "NSE",
    purchasePrice: 3300,
    quantity: 3,
    cmp: 0,
    peRatio: 0,
    earnings: "",
  },
  {
    symbol: "HCLTECH.NS",
    name: "HCL Technologies",
    sector: "Tech",
    exchange: "NSE",
    purchasePrice: 1350,
    quantity: 6,
    cmp: 0,
    peRatio: 0,
    earnings: "",
  },
  {
    symbol: "AXISBANK.NS",
    name: "Axis Bank",
    sector: "Financial",
    exchange: "NSE",
    purchasePrice: 980,
    quantity: 10,
    cmp: 0,
    peRatio: 0,
    earnings: "",
  },
];
